[package]
name = "wfc_3d"
version = "0.1.0"
authors = ["dcz <gilaac.dcz@porcupinefactory.org>"]
edition = "2021"
license = "LGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baustein = { path = "../baustein" }
