[package]
name = "baustein"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
building_blocks_mesh = "*" # depend on feldspar's version
feldspar-core = {path = "../../../feldspar/crates/feldspar-core"}
feldspar-map = {path = "../../../feldspar/crates/feldspar-map"}

[dependencies.ndshape]
git = "https://github.com/bonsairobo/ndshape-rs"
rev = "8fd240e"

[dependencies.feldspar] # same as domostroj
git = "https://github.com/bonsairobo/feldspar"
# branch = "main"
rev = "e09001c1"

[patch.'https://github.com/bonsairobo/feldspar']
feldspar = { path = "../../../feldspar" }
