[package]
name = "baustein"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feldspar-core = {path = "../../../feldspar/crates/feldspar-core"}
feldspar-map = {path = "../../../feldspar/crates/feldspar-map"}
ndshape = "*" # depend on feldspar-core
